const roles = {

    '/getAllUsers': ['admin'],
    '/getAllAuthors': ['admin'],
    '/getAllGenres': ['admin'],
    '/image': ['admin', "reader", 'author'],
    '/getAllNovels': ['admin'],
    '/admin-dashboard': ['admin'],
    '/addGenre': ['admin'],
    '/approve': ['admin'],
    '/reject': ['admin'],
    '/hideNovel': ['admin'],
    '/block-user': ['admin'],
    '/list-genre': ['admin'],
    '/edit-genre': ['admin'],


    '/getAuthorNovels': ['author'],
    '/getGenres': ['author', 'reader'],
    '/edit-chapter-details': ['author'],
    '/create': ['author'],
    '/addChapter': ['author'],
    '/payment-Eligible-Check': ['author'],
    '/cancel-novel': ['author'],
    '/delete-chapter': ['author'],
    '/edit-chapter': ['author'],
    '/getNovelDetailById': ['author'],
    '/edit-novel': ['author'],


    '/novelWithId': ['author', 'reader'],
    '/getAllNovels-user': ['author', 'reader'],
    '/get-library': ['author', 'reader'],
    '/getMostViewed': ['author', 'reader'],
    '/getNewUpdated': ['author', 'reader'],
    '/getTrending': ['author', 'reader'],
    '/getRandom': ['author', 'reader'],
    '/getWallet': ['author', 'reader'],
    '/check-GCoinSystem': ['author', 'reader'],
    '/all-message': ['author', 'reader'],
    '/checkPayToRead': ['author', 'reader'],
    '/get-community': ['author', 'reader'],
    '/create-payment-intent': ['author', 'reader'],
    '/add-To-library': ['author', 'reader'],
    '/filterNovels-user': ['author', 'reader'],
    '/payment-confirm': ['author', 'reader'],
    '/rateNovel': ['author', 'reader'],
    '/send-message': ['author', 'reader'],
    '/edit-profile': ['author', 'reader'],
    '/PayToReadPost': ['author', 'reader'],
    '/join-community': ['author', 'reader'],
    '/getChapter': ['author', 'reader'],

};

module.exports = roles